import sys
import os
from collections import Counter
import pandas as pd

def generate_pdf(df, output_path, summary_text, author_name):
    """Create a PDF report with summary and data table ."""
    from reportlab.lib.pagesizes import letter, landscape
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    from reportlab.lib.enums import TA_LEFT

    doc = SimpleDocTemplate(output_path, pagesize=landscape(letter),
                            leftMargin=0.5*inch, rightMargin=0.5*inch,
                            topMargin=0.5*inch, bottomMargin=0.5*inch)
    styles = getSampleStyleSheet()
    cell_style = ParagraphStyle(
        'CellStyle',
        parent=styles['Normal'],
        fontSize=7,
        leading=8,
        alignment=TA_LEFT,
        wordWrap='CJK'
    )

    story = []
    title_style = styles['Title']
    story.append(Paragraph(f"Company Insight Report – Generated by {author_name}", title_style))
    story.append(Spacer(1, 0.2*inch))

    for line in summary_text.split('\n'):
        if line.strip():
            story.append(Paragraph(line, styles['Normal']))
    story.append(Spacer(1, 0.2*inch))

    col_widths = [2.0*inch, 1.2*inch, 1.0*inch, 2.2*inch, 2.5*inch]
    header = [Paragraph(col, styles['Normal']) for col in df.columns.tolist()]
    data = [header]

    for _, row in df.iterrows():
        row_cells = [
            Paragraph(str(row['Company Name']), cell_style),
            Paragraph(str(row['Industry']), cell_style),
            Paragraph(str(row['Company Size']), cell_style),
            Paragraph(str(row['LinkedIn URL']), cell_style),
            Paragraph(str(row['Outsourcing Needs']), cell_style)
        ]
        data.append(row_cells)

    table = Table(data, colWidths=col_widths, repeatRows=1)
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.grey),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 8),
        ('BOTTOMPADDING', (0,0), (-1,0), 8),
        ('TOPPADDING', (0,0), (-1,0), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('LEFTPADDING', (0,0), (-1,-1), 4),
        ('RIGHTPADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(table)
    doc.build(story)
    print(f"PDF report saved to: {output_path}")

def load_data(filepath):
    """Load CSV and return DataFrame. Returns None if file not found."""
    if not os.path.isfile(filepath):
        print(f"Error: File '{filepath}' does not exist.")
        return None
    try:
        df = pd.read_csv(filepath)
        expected = ["Company Name", "Industry", "Company Size", "LinkedIn URL", "Outsourcing Needs"]
        for col in expected:
            if col not in df.columns:
                raise ValueError(f"Missing expected column: {col}")
        return df
    except Exception as e:
        print(f"Error reading file: {e}")
        return None

def apply_sort(df, sort_by):
    if sort_by:
        if isinstance(sort_by, str):
            sort_by = [sort_by]
        for col in sort_by:
            if col not in df.columns:
                print(f"Warning: Sort column '{col}' not found. Using 'Company Name'.")
                sort_by = ["Company Name"]
                break
        return df.sort_values(by=sort_by)
    return df

def apply_filters(df, industry=None, size=None, name_substring=None):
    if industry:
        df = df[df["Industry"].str.lower() == industry.lower()]
    if size:
        df = df[df["Company Size"].str.lower() == size.lower()]
    if name_substring:
        df = df[df["Company Name"].str.lower().str.contains(name_substring.lower())]
    return df

def generate_summary(df):
    lines = []
    lines.append("=== Company Data Summary ===")
    lines.append(f"Total companies: {len(df)}")

    industry_counts = df["Industry"].value_counts()
    lines.append("\n--- Industry Distribution ---")
    for ind, count in industry_counts.items():
        lines.append(f"  {ind}: {count}")

    size_counts = df["Company Size"].value_counts()
    lines.append("\n--- Company Size Distribution ---")
    for size, count in size_counts.items():
        lines.append(f"  {size}: {count}")

    all_needs = []
    for needs in df["Outsourcing Needs"].dropna():
        cleaned = needs.replace("Likely to outsource:", "").strip()
        for item in cleaned.split(","):
            item = item.strip()
            if item:
                all_needs.append(item)
    need_counts = Counter(all_needs)
    lines.append("\n--- Most Common Outsourcing Needs (Top 10) ---")
    for need, cnt in need_counts.most_common(10):
        lines.append(f"  {need}: {cnt}")

    lines.append("\n--- Industry-Specific Outsourcing Insights (AI-driven) ---")
    top_industries = industry_counts.head(5).index.tolist()
    for ind in top_industries:
        ind_df = df[df["Industry"] == ind]
        ind_needs = []
        for needs in ind_df["Outsourcing Needs"].dropna():
            cleaned = needs.replace("Likely to outsource:", "").strip()
            for item in cleaned.split(","):
                item = item.strip()
                if item:
                    ind_needs.append(item)
        if ind_needs:
            common = Counter(ind_needs).most_common(3)
            common_str = ", ".join([f"{need} ({cnt})" for need, cnt in common])
            lines.append(f"  {ind}: Top needs -> {common_str}")
        else:
            lines.append(f"  {ind}: No specific needs recorded.")

    return "\n".join(lines)

def save_report_csv_excel(df, output_path, format):
    if format.lower() == "csv":
        df.to_csv(output_path, index=False)
    elif format.lower() in ("excel", "xlsx"):
        df.to_excel(output_path, index=False)
    else:
        raise ValueError("Unsupported format for CSV/Excel save.")

def interactive_mode():
    print("\n=== Company Insight Processor – Interactive Menu ===\n")

    # Show current directory to help locate files
    cwd = os.getcwd()
    print(f"Current working directory: {cwd}")
    print("Files in this directory:")
    for f in os.listdir(cwd):
        print(f"  {f}")
    print("\n" + "-"*50 + "\n")

    author = input("Enter your name (for report header): ").strip()
    if not author:
        author = "Anonymous"

    default_input = "company_dataset_10000.csv"
    while True:
        inp = input(f"Enter input CSV file path (default: {default_input}): ").strip()
        if not inp:
            inp = default_input
        df = load_data(inp)
        if df is not None:
            break
        print("Please check the filename and try again.")

    default_output = "report.pdf"
    out = input(f"Enter output report file path (default: {default_output}): ").strip()
    if not out:
        out = default_output

    while True:
        print("\nFilter options:")
        print("  1. Filter by Company Name (substring)")
        print("  2. Filter by Industry (exact, case-insensitive)")
        print("  3. No filter (show all)")
        choice = input("Enter choice (1/2/3): ").strip()
        if choice in ('1','2','3'):
            break
        print("Invalid choice. Please enter 1, 2, or 3.")

    industry = None
    size = None
    name_substring = None

    if choice == '1':
        name_substring = input("Enter company name substring: ").strip()
    elif choice == '2':
        industry = input("Enter industry name: ").strip()

    # Optional size filter
    size_choice = input("Filter by Company Size? (y/n): ").strip().lower()
    if size_choice == 'y':
        size = input("Enter size (e.g., Micro, Small, Medium, Large, Enterprise): ").strip()

    # Sort column
    sort_col = input("Enter column to sort by (default: Company Name): ").strip()
    if not sort_col:
        sort_col = "Company Name"

    # Format
    fmt = input("Report format (csv/excel/pdf, default: pdf): ").strip().lower()
    if fmt not in ('csv','excel','pdf'):
        fmt = 'pdf'

    # Apply filters
    df_filtered = apply_filters(df, industry, size, name_substring)
    if df_filtered.empty:
        print("No data matches the filters. Exiting.")
        return

    # Apply sort
    df_sorted = apply_sort(df_filtered, sort_col)

    summary = generate_summary(df_sorted)
    print("\n" + summary)

    
    print("\n--- Preview (first 5 rows) ---")
    preview_df = df_sorted.head().copy()
    preview_df["LinkedIn URL"] = preview_df["LinkedIn URL"].apply(lambda x: x[:50] + "..." if len(str(x)) > 50 else x)
    print(preview_df.to_string(index=False))

    # Confirm save
    save = input("\nGenerate report? (y/n): ").strip().lower()
    if save != 'y':
        print("Report not generated.")
        return

    # Save
    if fmt == 'pdf':
        try:
            generate_pdf(df_sorted, out, summary, author)
        except ImportError:
            print("reportlab not installed. Install with: pip install reportlab", file=sys.stderr)
    else:
        try:
            save_report_csv_excel(df_sorted, out, fmt)
            print(f"Report saved to: {out}")
        except Exception as e:
            print(f"Error saving report: {e}", file=sys.stderr)

if __name__ == "__main__":
    interactive_mode()